---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  notify:
    - Restart Nginx

- name: Copy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart Nginx

- name: Deploy Website
  template:
    src: index.html.j2
    dest: "{{ nginx_root_dir }}/{{ nginx_index_file }}"
  notify:
    - Restart Nginx

- name: Ensure Nginx is enabled and running
  service:
    name: nginx
    enabled: yes
    state: started
